### ISSUE TITLE
Create a quest system plugin

### ISSUE THREAD

**Issue by anthony-maudry** [Kuchulem/RPG-Maker-MZ-Plugins#21]
# Kuchulem_Quests

A quest system that adds an item in the menu window.

## Usage

Quests are created either in a data file or in plugin parameters (to be decided). It could even be created "on the fly" with an event command.

If created in a data file, a tool may be developed to help makers.

Quest will be defined this way:

```
Quest:
  Title: (string)              // Displayed in the quest menu
  Description: (string)        // Displayed in the quest description
  State: (number)              // 0: inactive, 1: active, 2: completed, 3: failed
  Steps: QuestStep[]           // The steps to be finished to complete the quest
  Rewards: QuestReward         // The reward when the quest is completed

QuestStep:
  Index: (number)
  Title: (string)
  State: (number)
  Rewards: QuestReward

QuestReward:
  Xp: (number)
  Gold: (number)
  Items: number[]
  GlobalEvent: number
```

Players will receive quests from commands in events that will change the status of the quest.
